print('      x ')
print ('     xxx')
print ('    xxxxx')
print ('   xxxxxxx')
print('  xxxxxxxxx')
print(' xxxxxxxxxxx')
print('xxxxxxxxxxxxxxx')
print('xxxxxxxxxxxxxxxx')
print('      xx')
print('      xx')
print('      xxx')
